<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <AssemblyName>CsWebUi</AssemblyName>
    <RootNamespace>CsWebUi</RootNamespace>
    <NoWarn>$(NoWarn);1591;CA1720</NoWarn>
    <PackageId>CsWebUi</PackageId>
    <Title>CS-WebUI</Title>
    <Description>Safe, ergonomic .NET 10 window and callback abstractions for WebUI.</Description>
    <PackageTags>runic-artifex;webui;dotnet;bindings;aot;desktop</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CsWebUi.Native/CsWebUi.Native.csproj" />
    <None Update="README.md" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)..\..\assets\webui_csharp.png" Pack="true" PackagePath="assets/" />
    <None Include="$(MSBuildThisFileDirectory)..\..\eng\licenses\WebUI-Logo-LICENSE.txt" Pack="true" PackagePath="licenses/WebUI-Logo/" />
  </ItemGroup>
</Project>
